### PR TITLE
Trista recommendation menu

### PR DESCRIPTION
**Pull request by sitianqiu**
In this PR, I added menu in Nav Bar and wrote the Nav Tests.

### CODE REVIEW

**Comment by zackglazewski** [comment]
Did you remember to link to the index page in App.js?

**Comment by sitianqiu** [comment]
> Did you remember to link to the index page in App.js?

Yes, I did.

**Comment by sitianqiu** [comment]
> > Did you remember to link to the index page in App.js?
> 
> Yes, I did.

But I did it in another branch, I think that is the problem you wang to mention. I will fix it.

**Comment by sitianqiu** [comment]
> > > Did you remember to link to the index page in App.js?
> > 
> > 
> > Yes, I did.
> 
> But I did it in another branch, I think that is the problem you wang to mention. I will fix it.

NVM, we are supposed to add this in placeholder branch. I think I did nothing wrong here.

**Comment by crdgdr** [comment]
LGTM

**Pull request merged**
